[package]
name = "xed-sys"
version = "0.1.0"
authors = ["TA Thanh Dinh <tathanhdinh@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["staticlib"]

[dependencies]

[build-dependencies]
bindgen = "0.40.0"